SOCIAL_AUTH_TWITTER_KEY = 'dE0hrJeMAbToBlSzC7br7gzN6'
SOCIAL_AUTH_TWITTER_SECRET = 'KNkm5r5ix8u5vUmVK1vqBzALSYguHZwLbDj84qxAxIz2kPUtUp'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
